# Generated by Django 3.1.6 on 2021-04-11 17:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('pushup', 'pushup'), ('situp', 'situp'), ('pullup', 'pullup'), ('squat', 'squat'), ('burpee', 'burpee'), ('lift', 'lift'), ('run', 'run'), ('stretches', 'stretches'), ('other', 'other')], default='other', max_length=10)),
                ('date', models.DateField()),
                ('intensity', models.CharField(choices=[('light', 'light'), ('moderate', 'moderate'), ('vigorous', 'vigorous')], default='light', max_length=10)),
                ('duration', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
