# Generated by Django 3.1.5 on 2021-05-02 14:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('Pushup', 'Pushup'), ('Situp', 'Situp'), ('Pullup', 'Pullup'), ('Squat', 'Squat'), ('Burpee', 'Burpee'), ('Lift', 'Lift'), ('Run', 'Run'), ('Stretches', 'Stretches'), ('Other', 'Other')], default='Other', max_length=10)),
                ('date', models.DateField()),
                ('duration', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('intensity', models.CharField(choices=[('Light', 'Light'), ('Moderate', 'Moderate'), ('Vigorous', 'Vigorous')], default='Light', max_length=10)),
                ('area', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fitapp.logs')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
