# Generated by Django 3.1.2 on 2021-04-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='exercise',
            field=models.CharField(choices=[('Pushup', 'Pushup'), ('Situp', 'Situp'), ('Pullup', 'Pullup'), ('Squat', 'Squat'), ('Burpee', 'Burpee'), ('Lift', 'Lift'), ('Run', 'Run'), ('Stretches', 'Stretches'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='logs',
            name='intensity',
            field=models.CharField(choices=[('Light', 'Light'), ('Moderate', 'Moderate'), ('Vigorous', 'Vigorous')], default='Light', max_length=10),
        ),
    ]
