# Generated by Django 3.1.2 on 2021-03-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0003_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='value',
            field=models.IntegerField(default=60),
        ),
    ]
