# Generated by Django 3.1.2 on 2021-03-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0005_auto_20210331_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='value',
            field=models.IntegerField(default=20),
        ),
    ]
