# Generated by Django 3.1.2 on 2021-03-31 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0007_auto_20210331_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_custom',
        ),
    ]
