# Generated by Django 3.1.2 on 2021-03-31 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0008_auto_20210331_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current',
            new_name='value',
        ),
    ]
