# Generated by Django 3.1.2 on 2021-03-31 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0009_auto_20210331_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='value',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_custom',
            new_name='user',
        ),
    ]
