# Generated by Django 3.1.2 on 2021-04-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0010_auto_20210331_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('intensity', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='current',
            field=models.IntegerField(default=0),
        ),
    ]
