# Generated by Django 3.1.2 on 2021-04-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0011_auto_20210408_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.user'),
        ),
    ]
