# Generated by Django 3.1.2 on 2021-04-09 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitapp', '0012_logs_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='siteUser',
        ),
        migrations.AlterField(
            model_name='logs',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
