# Generated by Django 3.1.2 on 2021-04-10 16:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitapp', '0014_auto_20210409_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='siteUser',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='owner',
        ),
    ]
